version: "2"
plugins:
  swiftlint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - Pods
  - Extern
  - Beam/Classes/Helpers/Utils/Web/Readability.js
  - BeamTests
  - BeamUITests
