version: "2"
plugins:
  swiftlint:
    enabled: false
    channel: "stable"
  duplication:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
        - .ts
exclude_patterns:
  - Pods
  - Extern
  - Beam/Classes/Helpers/Utils/Web/Readability.js
  - "**/node_modules/"
  - BeamTests
  - BeamUITests
  - SourcePackages
  - fastlane
  - scripts
