stages:
  - test
  - build
  - notarize
  - dmg
  - zip
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_BRANCH: "$CI_COMMIT_REF_NAME"
  GIT_DEPTH: 10
  # Need to enable custom_build_dir feature
  # That generates IO errors
  # GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

cache:
  key:
    files:
      - Extern/libgit2
  paths:
    - Extern/libgit2/build/libgit2.a

include:
  - local: '.gitlab/ci/before-script-template.yml'
  - local: '.gitlab/ci/gitlab-ci-test.yml'
  - local: '.gitlab/ci/gitlab-ci-build.yml'
  - local: '.gitlab/ci/gitlab-ci-notarize.yml'
  - local: '.gitlab/ci/gitlab-ci-dmg.yml'
  - local: '.gitlab/ci/gitlab-ci-zip.yml'
  - local: '.gitlab/ci/gitlab-ci-deploy.yml'
  - local: '.gitlab/ci/gitlab-ci-publish.yml'
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  before_script:
    - date
    - echo "${CI_JOB_ID}"
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  timeout: 10 minutes
  artifacts:
    paths: [gl-code-quality-report.json]
    when: always
