stages:
  - xcode
  - test
  - build
  - notarize
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_BRANCH: "$CI_COMMIT_REF_NAME"
  # Need to enable custom_build_dir feature
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

before_script:
  # RVM install a `cd` :((((
  # Apparently the rvm(2.6.0), that I had installed previously, was overriding the cd bash command :expressionless:
  # https://forum.gitlab.com/t/self-hosted-gitlab-ci-runner-shell-executer-fails-immediately-with-error-job-failed-exit-status-1/33252/3
  - unset cd
  - direnv allow
  - eval "$(direnv export bash)"
  - eval "$(rbenv init -)"

include:
  - template: Code-Quality.gitlab-ci.yml
  - '.gitlab/ci/gitlab-ci-xcode.yml'
  - '.gitlab/ci/gitlab-ci-test.yml'
  - '.gitlab/ci/gitlab-ci-build.yml'
  - '.gitlab/ci/gitlab-ci-notarize.yml'
  - '.gitlab/ci/gitlab-ci-deploy.yml'

code_quality:
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
