coverage_service: cobertura_xml
output_directory: "./"
xcodeproj: Beam.xcodeproj
workspace: Beam.xcworkspace
scheme: Beam
source_directory: ./Beam
ignore:
  - "**/Pods/*"
  - "**/BeamTests/*"
  - "**/BeamUITests/*"
