custom_rules:
  print:
    name: "print"
    regex: 'print\(([^\)]*)\)'
    message: "Use Logger.shared.logDebug() instead"
    severity: warning
  date_init:
    name: "date_init"
    regex: '(:?\s|\()Date\(\)'
    message: "Use BeamDate.now instead"
    severity: warning

disabled_rules:
  - line_length
  - todo
  - comment_spacing
  - superfluous_disable_command
  - legacy_nsgeometry_functions

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
function_parameter_count: 6
type_body_length:
  - 300 # warning
  - 1000 # error
identifier_name:
  excluded:
    - id
    - me
  min_length: 1
  max_length: 45
  allowed_symbols: [_]
  validates_start_with_lowercase: false

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - fastlane
  - Extern
  - Beam/Classes/Helpers/Utils/Web/Readability.js
  - BeamTests
  - BeamUITests
  - SourcePackages
