custom_rules:
  print:
    name: "print()"
    regex: 'print\(([^\)]*)\)'
    message: "Use Logger.shared.logDebug() instead"
    severity: warning

# only the rules specified in this list will be enabled
only_rules:
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - fallthrough
  - file_length
  - for_where
  - force_cast
  - force_try
    # - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - custom_rules

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
function_parameter_count: 6
type_body_length:
  - 300 # warning
  - 1000 # error
identifier_name:
  excluded:
    - id
    - me
identifier_name:
    min_length: 1
    allowed_symbols: [_]
    validates_start_with_lowercase: false

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - fastlane
  - Extern
  - Beam/Classes/Helpers/Utils/Web/Readability.js
  - BeamTests
  - BeamUITests
  - SourcePackages
