platform :osx, '10.15'
use_frameworks!

inhibit_all_warnings!

target 'Beam' do
  pod 'SwiftLint'
  pod 'Down'
  pod 'Alamofire', '5.0.0.beta.6'
  pod 'JWTDecode'
  pod 'CocoaLumberjack/Swift'
  pod 'Sentry'
  pod 'AnyCodable-FlightSchool', '~> 0.4.0'
end

target 'BeamTests' do
  pod 'Fakery'
end
