xctests:
  timeout: 10 minutes
  dependencies: []
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - cobertura.xml
      - fastlane/test_output/tests.xml
      - logs
    reports:
      cobertura: cobertura.xml
      junit: fastlane/test_output/tests.xml
  coverage: '/Test Coverage\: \d+(?:\.\d*)?\%/'
  only:
    - merge_requests
    - master
    - develop
  script:
    - pwd
    - time bundle exec fastlane tests
  after_script:
    - rm "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Application Support/Beam/Beam-test-${CI_JOB_ID}"*
    - mkdir -p logs
    - mv ${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Logs/Beam/*.log logs
    - rm -r "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Logs/Beam/Vinyl/${CI_JOB_ID}"
  tags:
    - macos-mono
  interruptible: true

swift lint:
  timeout: 10 minutes
  dependencies: []
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - fastlane/codequality_report.json
    reports:
      codequality: fastlane/codequality_report.json
  script:
    - bundle exec fastlane lint
  only:
    - merge_requests
    - master
    - develop
  tags:
    - macos

xctests UI:
  timeout: 20 minutes
  dependencies: []
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - cobertura.xml
      - fastlane/test_output/tests.xml
      - screenshots
      - logs
    reports:
      cobertura: cobertura.xml
      junit: fastlane/test_output/tests.xml
  coverage: '/Test Coverage\: \d+(?:\.\d*)?\%/'
  only:
    - merge_requests
    - master
    - develop
  script:
    - time bundle exec fastlane uitests
  after_script:
    - xcparse screenshots --activity-type attachmentContainer userCreated testAssertionFailure --test --os --model fastlane/test_output/Beam.xcresult screenshots
    - xcparse screenshots --test-status Failure --test --os --model fastlane/test_output/Beam.xcresult screenshots
    - find screenshots -type d -empty -delete
    - rm "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Application Support/Beam/Beam-test-${CI_JOB_ID}"*
    - rm "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Application Support/GRDB-test-${CI_JOB_ID}"*
    - mkdir -p logs
    - mv ${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Logs/Beam/*.log logs
  tags:
    - macos-mono
  interruptible: true

coverage_check:
  dependencies: []
  stage: build
  needs: [xctests, xctests UI]
  only:
    - merge_requests
  script:
    - scripts/code_coverage.sh
  tags:
    - macos
  interruptible: true
  allow_failure: true
