swiftlint:
  dependencies: []
  stage: lint
  artifacts:
    expire_in: 7d
    paths:
      - fastlane/codequality_report_gitlab.json
    reports:
      codequality: fastlane/codequality_report_gitlab.json
  only:
    - merge_requests
  script:
    - bundle exec fastlane lint
    - scripts/codeclimate_converter.py
    - cat fastlane/codequality_report.json | sed -e "s|`pwd`/||" > fastlane/codequality_report_gitlab.json
  tags:
    - macos
  interruptible: true
  allow_failure: true
