build:macos:
  timeout: 10 minutes
  dependencies: []
  stage: build
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - merge_requests
    - master
    - develop
  script:
    - time bundle exec fastlane beta
  tags:
    - macos
  interruptible: true
  retry:
    max: 2
