sentry:
  timeout: 8 minutes
  dependencies:
    - build:macos
  stage: deploy
  artifacts:
    expire_in: 14d
    paths:
      - builds/
  rules:
    - if: '$SENTRY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - bundle exec fastlane ping_sentry --verbose
  tags:
    - macos-mono
  interruptible: true
  allow_failure: true
  retry:
    max: 2

build:upload:
  dependencies:
   - build:macos
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://s3.$AWS_DEFAULT_REGION.amazonaws.com/$S3_BUCKET/review/$CI_COMMIT_REF_NAME/Beam.dmg
    on_stop: build:cleanup
  artifacts:
    expire_in: 14d
    paths:
      - builds/
  rules:
    - if: '$S3_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - bundle exec fastlane deploy
  tags:
    - macos-mono
  interruptible: false
  retry:
    max: 2

build:cleanup:
  dependencies: []
  stage: deploy
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
      when: never
  when: manual
  script:
    - bundle exec fastlane delete_s3
  tags:
    - macos-mono
  interruptible: false
  retry:
    max: 2

build:cleanup:derived_data:
  timeout: 10 minutes
  dependencies: []
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - bundle exec fastlane delete_s3_derived_data
  tags:
    - macos-mono
  interruptible: true
  allow_failure: true

cherry_pick_to_develop:
  timeout: 2 minutes
  image: registry.gitlab.com/beamgroup/beam/curl-jq
  before_script:
    - date
  dependencies: []
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
  script:
    - scripts/handle_cherry_pick.sh
  interruptible: true
  allow_failure: true
