release:
  stage: deploy
  dependencies:
    - notarize
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - master
    - develop
    - merge_requests
  before_script:
    - echo "${PATH}"
    - pwd
    - unset cd
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
  script:
    - bundle exec fastlane publish_release
  tags:
    - macos
  interruptible: true
  allow_failure: false
  when: manual
