build:dmg:
  dependencies:
    - notarize
  stage: dmg
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  rules:
    - if: '$BUILD_DMG_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - echo "${PATH}"
    - pwd
  script:
    - ./scripts/build_dmg.sh
  tags:
    - macos-mono
  interruptible: true
  retry:
    max: 2
