build:publish:
  stage: deploy
  dependencies:
    - build:macos
  before_script:
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
    - bundle install
    # So that we can push tags
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -re "s|https?://gitlab-ci-token:.*@|https://${GITLAB_BOT_USERNAME}:${GITLAB_BOT_ACCESS_TOKEN}@|g")
    - git remote set-url --push origin "${url_host}"
  artifacts:
    expire_in: 14d
    paths:
      - builds/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
  when: manual
  script:
    - bundle exec fastlane publish
  tags:
    - macos-mono
  interruptible: true
  allow_failure: true
