release:
  stage: deploy
  dependencies:
    - notarize
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - master
    - develop
    - merge_requests
  script:
    - bundle exec fastlane publish_release
  tags:
    - macos
  interruptible: true
  allow_failure: true
  when: manual
