notarize:
  dependencies:
    - build:macos
  stage: notarize
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - merge_requests
    - master
    - develop
  script:
    - ./scripts/build_dmg.sh
    - bundle exec fastlane notarize_build
  tags:
    - macos
  interruptible: true
