build:upload:
  dependencies:
   - build:macos
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://s3.$AWS_DEFAULT_REGION.amazonaws.com/$S3_BUCKET/review/$CI_COMMIT_REF_NAME/Beam.dmg
    on_stop: build:cleanup
  before_script:
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
    - bundle install
    # So that we can push tags
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -re "s|https?://gitlab-ci-token:.*@|https://${GITLAB_BOT_USERNAME}:${GITLAB_BOT_ACCESS_TOKEN}@|g")
    - git remote set-url --push origin "${url_host}"
  artifacts:
    expire_in: 14d
    paths:
      - builds/
    exclude:
      - builds/Beam.app/**
      - builds/**.dmg
      - builds/**.zip
  rules:
    - if: '$S3_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
  script:
    - bundle exec fastlane deploy
  tags:
    - macos-mono
  interruptible: false
  retry:
    max: 2

build:cleanup:
  dependencies: []
  needs: ["build:macos"]
  stage: deploy
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
  when: manual
  script:
    - bundle exec fastlane delete_s3
  tags:
    - macos-mono
  interruptible: false
  retry:
    max: 2
