swiftlint:
  dependencies: []
  stage: lint
  artifacts:
    expire_in: 7d
    paths:
      - fastlane/codequality_report_gitlab.json
      - fastlane/codequality_report.json
      - fastlane/swiftlint.json
    reports:
      codequality: fastlane/codequality_report_gitlab.json
  only:
    - merge_requests
    - master
  script:
    - bundle exec fastlane lint
  after_script:
    - scripts/codeclimate_converter.py
    - cat fastlane/codequality_report.json | sed -e "s|`pwd`/||" > fastlane/codequality_report_gitlab.json
  tags:
    - macos
  interruptible: true

#code_quality:
#  artifacts:
#    reports:
#      codequality: fastlane/codequality_report.json
