swift lint:
  timeout: 5 minutes
  dependencies: []
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    when: always
    paths:
      - fastlane/codequality_report.json
    reports:
      codequality: fastlane/codequality_report.json
  script:
    - bundle exec fastlane lint
  rules:
    - if: '$SWIFT_LINT_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
  tags:
    - macos-mono

build:macos:
  timeout: 15 minutes
  dependencies: []
  stage: build
  artifacts:
    expire_in: 14d
    paths:
      - builds/
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - |-
        time bundle exec fastlane build
        if [[ ! ${BUILD_DMG_DISABLED} ]]
        then
          bundle exec fastlane notarize_build
          ./scripts/build_dmg.sh
        fi
        if [[ ! ${BUILD_ZIP_DISABLED} ]]
        then
          ./scripts/build_zip.sh
        fi
        if [[ ! ${SENTRY_DISABLED} ]]
        then
          bundle exec fastlane ping_sentry --verbose
        fi
  tags:
    - macos-mono
  interruptible: true
  retry:
    max: 2

cherry_pick_to_develop:
  image: registry.gitlab.com/beamgroup/beam/curl-jq
  before_script:
    - date
  dependencies: []
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
  script:
    - scripts/handle_cherry_pick.sh
  after_script:
    - if [ ${CI_JOB_STATUS} == "failed" ]; then source ./scripts/cherry_pick_failure_slack_notif.sh; share_slack_update; fi
  interruptible: true
  allow_failure: true
