build:zip:
  dependencies:
    - build:dmg
  stage: zip
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  rules:
    - if: '$BUILD_ZIP_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - echo "${PATH}"
    - pwd
  script:
    - ./scripts/build_zip.sh
  tags:
    - macos
  interruptible: true
  retry:
    max: 2
