build:zip:
  dependencies:
    - build:dmg
  stage: zip
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - merge_requests
    - master
    - develop
  before_script:
    - echo "${PATH}"
    - pwd
  script:
    - ./scripts/build_zip.sh
  tags:
    - macos
  interruptible: true
  retry:
    max: 2
