build:macos:
  dependencies: []
  stage: build
  artifacts:
    expire_in: 7d
    paths:
      - builds/
  only:
    - merge_requests
    - master
    - develop
  before_script:
    - echo "${PATH}"
    - pwd
    - unset cd
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
    - xcversion update
    - xcversion install ${XCODE_VERSION}
    - bundle install
  script:
    - time bundle exec fastlane beta
  tags:
    - macos
  interruptible: true
  retry:
    max: 2
