xctests:
  dependencies: []
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - cobertura.xml
      - fastlane/test_output/tests.xml
      - builds
    reports:
      cobertura: cobertura.xml
      junit: fastlane/test_output/tests.xml
  coverage: '/Test Coverage\: \d+(?:\.\d*)?\%/'
  only:
    - merge_requests
    - master
    - develop
  before_script:
    - echo "${PATH}"
    - pwd
    - unset cd
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
    - xcversion update
    - xcversion install ${XCODE_VERSION}
    - bundle install
  script:
    - pwd
    - time bundle exec fastlane tests
  after_script:
    - rm "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Application Support/Beam/Beam-test-${CI_JOB_ID}"*
  tags:
    - macos
  interruptible: true

xctests UI:
  dependencies: []
  stage: test
  artifacts:
    expire_in: 7d
    when: always
    paths:
      - cobertura.xml
      - fastlane/test_output/tests.xml
      - builds
      - screenshots
    reports:
      cobertura: cobertura.xml
      junit: fastlane/test_output/tests.xml
  coverage: '/Test Coverage\: \d+(?:\.\d*)?\%/'
  only:
    - merge_requests
    - master
    - develop
  before_script:
    - echo "${PATH}"
    - pwd
    - unset cd
    - direnv allow
    - eval "$(direnv export bash)"
    - eval "$(rbenv init -)"
    - xcversion update
    - xcversion install ${XCODE_VERSION}
    - bundle install
  script:
    - time bundle exec fastlane uitests
  after_script:
    - xcparse screenshots --activity-type attachmentContainer userCreated testAssertionFailure --test --os --model fastlane/test_output/Beam.xcresult screenshots
    - xcparse screenshots --test-status Failure --test --os --model fastlane/test_output/Beam.xcresult screenshots
    - find screenshots -type d -empty -delete
    - rm "${HOME}/Library/Containers/co.beamapp.macos/Data/Library/Application Support/Beam/Beam-test-${CI_JOB_ID}"*
  tags:
    - macos-mono
  interruptible: true

coverage_check:
  dependencies: []
  stage: build
  needs: [xctests, xctests UI]
  only:
    - merge_requests
  script:
    - scripts/code_coverage.sh
  tags:
    - macos
  interruptible: true
  allow_failure: true
