build:macos:
  timeout: 10 minutes
  dependencies: []
  stage: build
  artifacts:
    expire_in: 14d
    paths:
      - builds/
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^beta-.+/'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.+/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - |-
        time bundle exec fastlane build
        if [[ ! ${BUILD_DMG_DISABLED} ]]
        then
          bundle exec fastlane notarize_build
          ./scripts/build_dmg.sh
        fi
        if [[ ! ${BUILD_ZIP_DISABLED} ]]
        then
          ./scripts/build_zip.sh
        fi
  tags:
    - macos-mono
  interruptible: true
  retry:
    max: 2
